[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[test]
skip-deploy = false
script = "yarn test"

[programs.localnet]
market_migration_task = "ExponentnaRg3CQbW6dqQNZKXp7gtZ9DGMp1cwC4HAS7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"


