name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  migration-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1

       # 6) Install Anchor CLI via composite action
      - name: Install Anchor CLI
        uses: metaDAOproject/setup-anchor@v1
        with:
          solana-cli-version: "1.18.15"
          node-version: "23.11.0"
          anchor-version: "0.31.1"
        
      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Build program (simple)
        run: yarn build-simple-test

      - name: Run simple tests
        run: yarn test --skip-lint

      - name: Build program (migration)
        run: yarn build-migration

      - name: Run migration tests
        run: yarn test --skip-lint
