name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  migration-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      # 2) Node.js 23.11.0
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23.11.0"

      - name: Enable Corepack and set Yarn version
        run: |
          corepack enable
          corepack prepare yarn@4.9.1 --activate

      - name: Cache Solana CLI tools
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/solana/
            ~/.local/share/solana/
          key: solana-cli-${{ runner.os }}-build-$2.2.14
      - name: Install Solana CLI tools
        # Use the old solana.com release if the version starts with 1, Anza otherwise
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/v2.2.14/install)"
        shell: bash
      - name: Update PATH
        run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
        shell: bash
        # 4) Install Anchor CLI (latest)

      - name: Install Anchor CLI
        run: npm i -g @coral-xyz/anchor-cli@0.31.1
        shell: bash

      - name: Build program (simple)
        run: yarn build-simple-test

      - name: Run simple tests
        run: yarn test --skip-lint

      - name: Build program (migration)
        run: yarn build-migration

      - name: Run migration tests
        run: yarn test --skip-lint
