name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  migration-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

       # 1) Rust (nightly 1.88.0)
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: 1.88.0-nightly
          override: true

      # 2) Node.js 23.11.0
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23.11.0

      # 3) Solana CLI 2.2.12
      - name: Install Solana CLI
        run: |
          curl -sSfL https://release.solana.com/v2.2.12/install | sh
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Build anchor-bankrun fork
        run: |
          yarn install
          yarn build-anchor-bankrun
          yarn install